In [ ]:
df["temperature"].hist(bins=30)
plt.title("Temperature Distribution")
plt.xlabel("Temperature")
plt.ylabel("Frequency")
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df["vibration"].hist(bins=30)
plt.title("Vibration Distribution")
plt.xlabel("Vibration")
plt.ylabel("Frequency")
plt.show()

In [ ]:
df["pressure"].hist(bins=30)
plt.title("Pressure Distribution")
plt.xlabel("Pressure")
plt.ylabel("Frequency")
plt.show()

In [ ]:
plt.boxplot(df["temperature"])
plt.title("Temperature Boxplot")
plt.show()

In [ ]:
plt.boxplot(df["pressure"])
plt.title("Pressure Boxplot")
plt.show()

In [ ]:
plt.boxplot(df["vibration"])
plt.title("Vibration Boxplot")
plt.show()

In [ ]:
corr = df.corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True)
plt.title("Correlation Heatmap")
plt.show()

In [7]:
df["failure"].value_counts()

failure
0.0    9999
1.0       1
Name: count, dtype: int64

In [8]:
df = pd.read_csv("../data/sensor_data.csv")
df.head()

   time  temperature  vibration    pressure  failure_warning  failure
0     0    70.993428  20.348286   90.097140              0.0      0.0
1     1    69.723471  20.283324   94.725072              0.0      0.0
2     2    71.295377  19.063480   97.064858              0.0      0.0
3     3    73.046060  20.579584  100.748345              0.0      0.0
4     4    69.531693  18.509917  105.120812              0.0      0.0

In [ ]:


# - The dataset contains 10,000 time-ordered observations.
# - The target `failure_warning` is imbalanced: 8% warnings and 92% normal observations.
# - The real `failure` column contains only one actual failure, so it is not suitable as the main training target.
# - Temperature, vibration, and pressure show abnormal maximum values compared to their normal operating ranges.
# - The next step is feature engineering and preparing time-series sequences for LSTM training.

In [4]:
df.describe()

,time,temperature,vibration,pressure,failure_warning,failure
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000
mean,4999.50000,70.245728,20.137537,100.262143,0.080000,0.0001
std,2886.89568,2.853816,1.570052,5.572422,0.271307,0.0100
min,0.00000,62.155199,16.344913,77.671981,0.000000,0.0000
25%,2499.75000,68.686719,19.315953,96.587714,0.000000,0.0000
50%,4999.50000,70.039145,20.013075,100.068628,0.000000,0.0000
75%,7499.25000,71.418977,20.703655,103.589713,0.000000,0.0000
max,9999.00000,98.330285,36.840939,137.080866,1.000000,1.0000

In [6]:
df["failure_warning"].value_counts()

failure_warning
0.0    9200
1.0     800
Name: count, dtype: int64

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             10000 non-null  int64
 1   temperature      10000 non-null  float64
 2   vibration        10000 non-null  float64
 3   pressure         10000 non-null  float64
 4   failure_warning  10000 non-null  float64
 5   failure          10000 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 468.9 KB

In [ ]:
df.shape

(10000, 6)

In [1]:
import pandas as pd

df = pd.read_csv("../data/sensor_data.csv")

df.head()

   time  temperature  vibration    pressure  failure_warning  failure
0     0    70.993428  20.348286   90.097140              0.0      0.0
1     1    69.723471  20.283324   94.725072              0.0      0.0
2     2    71.295377  19.063480   97.064858              0.0      0.0
3     3    73.046060  20.579584  100.748345              0.0      0.0
4     4    69.531693  18.509917  105.120812              0.0      0.0